version: "3.8"

services:
  api:
    build: ./backend/api/
    working_dir: /backend/api/
    environment:
      - "ADMIN_TOKEN=$ADMIN_TOKEN"
      - "ALLOWED_CORS_ORIGIN=$ALLOWED_CORS_ORIGIN"
      - "AUTH0_AUDIENCE=$AUTH0_AUDIENCE"
      - "AUTH0_DOMAIN=$AUTH0_DOMAIN"
      - "AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID"
      - "AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET"
      - "CLOUD_ENV=$CLOUD_ENV"
      - "DB_USERNAME=$DB_USERNAME"
      - "DB_PASSWORD=$DB_PASSWORD"
      - "DB_HOST_URL=$DB_HOST_URL"
      - "DB_NAME=$DB_NAME"
      - "DRAGONDROP_API_PATH=$DRAGONDROP_API_PATH"
      - "FLASK_HOST=$FLASK_HOST"
      - "FRONT_END_ROOT=$FRONT_END_ROOT"
      - "GITHUB_APP_ID=$GITHUB_APP_ID"
      - "GITHUB_PRIVATE_KEY=$GITHUB_PRIVATE_KEY"
      - "INFRACOST_API_TOKEN=$INFRACOST_API_TOKEN"
      - "SENDGRID_API_KEY=$SENDGRID_API_KEY"
      - "SENDGRID_GROUP_IDS_MAP=$SENDGRID_GROUP_IDS_MAP"
      - "SENDGRID_WELCOME_TEMPLATE=$SENDGRID_WELCOME_TEMPLATE"
      - "SENDGRID_INVITE_TEMPLATE=$SENDGRID_INVITE_TEMPLATE"
      - "SENDGRID_GROUP_IDS=$SENDGRID_GROUP_IDS"
      - "PUBLIC_SUPPORT_URL=$PUBLIC_SUPPORT_URL"
      - "STRIPE_API_TOKEN=$STRIPE_API_TOKEN"
      - "STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET"
      - "STRIPE_DEFAULT_FREE_PRODUCT_ID=$STRIPE_DEFAULT_FREE_PRODUCT_ID"
    networks:
      - network
    ports:
      - "5000:5000"
    depends_on:
      - "db-local"

