version: "3.8"

services:
  api:
    build: .
    environment:
      - "SENDGRIDAPITOKEN=$SENDGRIDAPITOKEN"
      - "SENDGRIDEMAILTEAMPLATEID=$SENDGRIDEMAILTEAMPLATEID"
      - "STRIPEWEBHOOKSECRET=$STRIPEWEBHOOKSECRET"
    ports:
      - "8080:8080"
